'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Theme} from '@astryxdesign/core/theme';
import {neutralTheme} from '@astryxdesign/theme-neutral/built';
import {Button} from '@astryxdesign/core/Button';
import {Card} from '@astryxdesign/core/Card';
import {TextInput} from '@astryxdesign/core/TextInput';
import {ChatComposer,ChatMessage,ChatMessageBubble,ChatMessageList} from '@astryxdesign/core/Chat';
import {Camera,ChevronRight,CircleDollarSign,FileText,Home,Landmark,Mail,MessageCircleMore,Plus,ReceiptText,School,ShoppingBag,Sparkles,Upload,Wallet,WalletCards,Zap} from 'lucide-react';

type View='home'|'activity'|'add'|'accounts'|'ask';
type Tx={id:string,name:string,amount:number,date:string,category:string,source:string,notes?:string};
type Msg={role:'user'|'assistant',text:string};
const base:Tx[]=[
{id:'1',name:'Jumbo',amount:84320,date:'2026-09-26',category:'Supermercado',source:'Visa Santander'},
{id:'2',name:'YPF',amount:46800,date:'2026-09-25',category:'Nafta',source:'Mercado Pago'},
{id:'3',name:'EDEA',amount:61240,date:'2026-09-24',category:'Servicios',source:'Débito Galicia'},
{id:'4',name:'Netflix',amount:15499,date:'2026-09-23',category:'Suscripciones',source:'Mastercard BBVA'},
{id:'5',name:'Colegio San José',amount:185000,date:'2026-09-15',category:'Educación',source:'Transferencia Galicia'},
{id:'6',name:'Camuzzi',amount:28930,date:'2026-09-10',category:'Servicios',source:'Débito Santander'}
];
const money=(n:number)=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(n);
export default function Page(){
 const [view,setView]=useState<View>('home'); const [txs,setTxs]=useState<Tx[]>(base); const [msgs,setMsgs]=useState<Msg[]>([]); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState('');
 const [manual,setManual]=useState({name:'',amount:'',category:'',source:'Efectivo'}); const scanRef=useRef<HTMLInputElement>(null); const pdfRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{const saved=localStorage.getItem('cifra.txs'); if(saved) try{setTxs(JSON.parse(saved))}catch{}},[]);
 useEffect(()=>{localStorage.setItem('cifra.txs',JSON.stringify(txs))},[txs]);
 const total=useMemo(()=>txs.reduce((s,t)=>s+t.amount,0),[txs]);
 const addTx=(t:Omit<Tx,'id'>)=>setTxs(v=>[{...t,id:crypto.randomUUID()},...v]);
 const ask=async(q:string)=>{if(!q.trim()||busy)return; setMsgs(v=>[...v,{role:'user',text:q}]);setBusy(true);try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q,context:{transactions:txs,summary:{total,upcoming:[{name:'Visa Santander',date:'2026-10-03',amount:684320},{name:'Colegio San José',date:'2026-10-05',amount:185000},{name:'EDEA + Camuzzi',date:'2026-10-08',amount:90170}]}}})});const d=await r.json();setMsgs(v=>[...v,{role:'assistant',text:d.answer||d.error||'No pude responder.'}])}catch{setMsgs(v=>[...v,{role:'assistant',text:'No pude conectar con el servidor.'}])}finally{setBusy(false)}};
 const scan=async(file:File)=>{setBusy(true);setNotice('Leyendo comprobante…');try{const image=await fileToDataUrl(file);const r=await fetch('/api/receipt',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image})});const d=await r.json();if(!r.ok)throw new Error(d.error);const x=d.result;addTx({name:x.merchant||'Comprobante',amount:Number(x.amount)||0,date:x.date||new Date().toISOString().slice(0,10),category:x.category||'Otros',source:x.paymentMethod||'Ticket escaneado',notes:x.notes||''});setNotice(`Listo: ${x.merchant||'comprobante'} · ${money(Number(x.amount)||0)}`)}catch(e){setNotice(e instanceof Error?e.message:'No pude leer el ticket.')}finally{setBusy(false)}};
 const pdf=async(file:File)=>{setBusy(true);setNotice('Analizando PDF…');try{const f=new FormData();f.append('file',file);const r=await fetch('/api/pdf',{method:'POST',body:f});const d=await r.json();if(!r.ok)throw new Error(d.error);const arr=Array.isArray(d.result.transactions)?d.result.transactions:[];arr.forEach((x:any)=>addTx({name:x.merchant||'Movimiento PDF',amount:Number(x.amount)||0,date:x.date||new Date().toISOString().slice(0,10),category:x.category||'Otros',source:file.name,notes:x.notes||''}));setNotice(`${d.result.summary||'PDF analizado'}. Importé ${arr.length} movimientos.`)}catch(e){setNotice(e instanceof Error?e.message:'No pude analizar el PDF.')}finally{setBusy(false)}};
 return <Theme theme={neutralTheme} mode="light"><main className="shell"><header className="top"><div><span className="eyebrow">CIFRA</span><h1>{view==='home'?'Tu plata, explicada.':view==='activity'?'Tus movimientos':view==='add'?'Agregar información':view==='accounts'?'Tus fuentes':'Preguntá lo que quieras'}</h1></div><button className="account-btn" onClick={()=>setView('accounts')}><Wallet size={19}/></button></header>
 {view==='home'&&<HomeView total={total} txs={txs} go={setView}/>} {view==='activity'&&<Activity txs={txs}/>} {view==='add'&&<Add manual={manual} setManual={setManual} addTx={addTx} scanRef={scanRef} pdfRef={pdfRef} scan={scan} pdf={pdf} notice={notice} busy={busy}/>} {view==='accounts'&&<Accounts go={setView}/>} {view==='ask'&&<Ask msgs={msgs} ask={ask} busy={busy}/>} 
 <nav className="nav"><Nav icon={Home} label="Inicio" active={view==='home'} click={()=>setView('home')}/><Nav icon={ReceiptText} label="Gastos" active={view==='activity'} click={()=>setView('activity')}/><button className="plus" onClick={()=>setView('add')}><Plus size={24}/></button><Nav icon={WalletCards} label="Fuentes" active={view==='accounts'} click={()=>setView('accounts')}/><Nav icon={MessageCircleMore} label="Preguntá" active={view==='ask'} click={()=>setView('ask')}/></nav></main></Theme>
}
function HomeView({total,txs,go}:{total:number;txs:Tx[];go:(v:View)=>void}){return <section className="stack"><div className="story hero"><span>Este mes</span><strong>{money(total)}</strong><p>Tenés todo lo que cargamos hasta hoy en un mismo lugar. No hace falta mirar seis apps para entender qué pasó.</p></div><div className="story lavender"><Sparkles/><div><b>Lo importante ahora</b><p>Antes del 8 de octubre necesitás aproximadamente <strong>$959.490</strong> para Visa Santander, colegio y servicios.</p></div></div><div className="story peach"><School/><div><b>Colegio ya pesa en el mes</b><p>La cuota de $185.000 está registrada y vuelve a aparecer el 5 de octubre.</p></div></div><div className="story mint"><Zap/><div><b>Servicios vienen subiendo</b><p>Luz, gas, teléfono e internet suman más que hace tres meses. Cifra te va a avisar cuando cambie algo fuera de lo normal.</p></div></div><div className="section-title"><h2>Últimos gastos</h2><button onClick={()=>go('activity')}>Ver todos</button></div><TxList items={txs.slice(0,5)}/><div className="section-title"><h2>Sumá lo que falta</h2></div><button className="wide-action" onClick={()=>go('add')}><span><Upload/></span><div><b>Ticket, PDF, banco, billetera o manual</b><small>Cualquier origen termina en la misma historia.</small></div><ChevronRight/></button></section>}
function Activity({txs}:{txs:Tx[]}){return <section className="stack"><Card padding={4}><div className="plain-summary"><span>Lo que registraste</span><strong>{money(txs.reduce((s,t)=>s+t.amount,0))}</strong><small>{txs.length} movimientos en distintas fuentes</small></div></Card><TxList items={txs}/></section>}
function TxList({items}:{items:Tx[]}){return <div className="tx-list">{items.map(t=><div className="tx" key={t.id}><span className="tx-icon"><ShoppingBag size={17}/></span><div><b>{t.name}</b><small>{t.category} · {t.source}</small></div><strong>{money(t.amount)}</strong></div>)}</div>}
function Add({manual,setManual,addTx,scanRef,pdfRef,scan,pdf,notice,busy}:{manual:any;setManual:any;addTx:any;scanRef:any;pdfRef:any;scan:any;pdf:any;notice:string;busy:boolean}){return <section className="stack"><p className="lead">Elegí de dónde viene el gasto. Todo queda editable y entra al mismo historial.</p><div className="source-grid"><Source icon={Camera} title="Escanear ticket / QR" copy="Usa la cámara y reconoce los datos" click={()=>scanRef.current?.click()}/><Source icon={FileText} title="Subir PDF" copy="Resumen, factura o banco" click={()=>pdfRef.current?.click()}/><Source icon={Mail} title="Conectar mail" copy="Facturas y comprobantes" click={()=>alert('La conexión Gmail/Outlook queda lista para OAuth en la siguiente etapa.')}/><Source icon={Landmark} title="Conectar banco" copy="Santander, Galicia, BBVA…" click={()=>alert('La conexión bancaria requiere proveedor Open Banking. La interfaz ya está preparada.')}/><Source icon={Wallet} title="Conectar billetera" copy="Mercado Pago, Ualá y más" click={()=>alert('La conexión de billeteras requiere autorización del proveedor.')}/><Source icon={CircleDollarSign} title="Carga manual" copy="Para efectivo o lo que quieras" click={()=>document.getElementById('manual')?.scrollIntoView({behavior:'smooth'})}/></div><input ref={scanRef} hidden type="file" accept="image/*" capture="environment" onChange={e=>e.target.files?.[0]&&scan(e.target.files[0])}/><input ref={pdfRef} hidden type="file" accept="application/pdf" onChange={e=>e.target.files?.[0]&&pdf(e.target.files[0])}/>{notice&&<div className="notice">{busy?'Procesando… ':''}{notice}</div>}<Card padding={4}><div id="manual" className="manual"><h2>Carga manual</h2><TextInput label="Concepto" value={manual.name} onChange={(v:string)=>setManual({...manual,name:v})} width="100%"/><TextInput label="Importe" value={manual.amount} onChange={(v:string)=>setManual({...manual,amount:v})} width="100%"/><TextInput label="Categoría" value={manual.category} onChange={(v:string)=>setManual({...manual,category:v})} width="100%"/><Button label="Guardar gasto" variant="primary" width="100%" onClick={()=>{if(!manual.name||!manual.amount)return;addTx({name:manual.name,amount:Number(String(manual.amount).replace(/\D/g,'')),date:new Date().toISOString().slice(0,10),category:manual.category||'Otros',source:manual.source});setManual({name:'',amount:'',category:'',source:'Efectivo'})}}/></div></Card></section>}
function Accounts({go}:{go:(v:View)=>void}){const acc=[['Santander','Cuenta + Visa','$ 1.284.300','rose'],['Banco Galicia','Caja de ahorro','$ 842.900','orange'],['BBVA','Mastercard','$ 386.120','blue'],['Mercado Pago','Billetera','$ 214.800','cyan'],['Ualá','Billetera','$ 98.700','violet']];return <section className="stack"><p className="lead">Tus cuentas no se mezclan: Cifra reúne la información para explicarte el total.</p>{acc.map(a=><button className={`account ${a[3]}`} key={a[0]}><span><Landmark/></span><div><b>{a[0]}</b><small>{a[1]}</small></div><strong>{a[2]}</strong><ChevronRight/></button>)}<Button label="Agregar otra fuente" variant="primary" width="100%" onClick={()=>go('add')}/></section>}
function Ask({msgs,ask,busy}:{msgs:Msg[];ask:(q:string)=>void;busy:boolean}){const prompts=['¿Cuánto tengo que pagar la primera semana de octubre?','¿Cuánto gasté en colegio?','¿Qué gastos se repiten todos los meses?','¿Dónde gasté más esta semana?'];return <section className="ask"><div className="ask-intro"><span><Sparkles/></span><h2>Hablá con tus propios gastos.</h2><p>Preguntá como hablarías con una persona. Cifra usa sólo los datos que cargaste.</p></div><div className="prompt-grid">{prompts.map(p=><Button key={p} label={p} variant="secondary" size="sm" onClick={()=>ask(p)}/>)}</div><div className="chat-zone"><ChatMessageList align="top" density="compact">{msgs.map((m,i)=><ChatMessage key={i} sender={m.role==='user'?'user':'assistant'}><ChatMessageBubble>{m.text}</ChatMessageBubble></ChatMessage>)}</ChatMessageList></div><div className="composer"><ChatComposer onSubmit={ask} isDisabled={busy} placeholder={busy?'Pensando…':'Preguntá sobre tus gastos…'} density="balanced" elevation="low"/></div></section>}
function Source({icon:Icon,title,copy,click}:{icon:any;title:string;copy:string;click:()=>void}){return <button className="source" onClick={click}><span><Icon/></span><b>{title}</b><small>{copy}</small></button>}
function Nav({icon:Icon,label,active,click}:{icon:any;label:string;active:boolean;click:()=>void}){return <button className={active?'active':''} onClick={click}><Icon size={19}/><span>{label}</span></button>}
function fileToDataUrl(file:File){return new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=reject;r.readAsDataURL(file)})}
